name: Deploy Fullstack to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/elearning-platform
            git pull origin develop
            
            cd frontend
            echo "VITE_API_URL=/api" > .env
            echo "VITE_GOOGLE_CLIENT_ID=781175488258-6nbe2tvspmc3p2dk42dkt7t94scf6p8d.apps.googleusercontent.com" >> .env
            
            cd ..
            docker-compose up -d --build
